test_that("empty_to_null works", {
  expect_identical(empty_to_null(NULL), NULL)
  expect_identical(empty_to_null(NA), NA)
  expect_identical(empty_to_null(""), NULL)
  expect_identical(empty_to_null(list()), NULL)
  expect_identical(empty_to_null(c()), NULL)
  expect_identical(empty_to_null(character(0)), NULL)
  expect_identical(empty_to_null(character(1)), NULL)
  expect_identical(empty_to_null(numeric(0)), NULL)
  expect_identical(empty_to_null(numeric(1)), 0)
  expect_identical(empty_to_null("a"), "a")
  expect_identical(empty_to_null(character(2)), c("", ""))
  expect_identical(empty_to_null(0), 0)
})

test_that("is_empty works", {
  expect_identical(is_empty(NULL), TRUE)
  expect_identical(is_empty(NA), FALSE)
  expect_identical(is_empty(""), TRUE)
  expect_identical(is_empty(list()), TRUE)
  expect_identical(is_empty(c()), TRUE)
  expect_identical(is_empty(character(0)), TRUE)
  expect_identical(is_empty(character(1)), TRUE)
  expect_identical(is_empty(numeric(0)), TRUE)
  expect_identical(is_empty(numeric(1)), FALSE)
  expect_identical(is_empty("a"), FALSE)
  expect_identical(is_empty(character(2)), FALSE)
  expect_identical(is_empty(0), FALSE)
})
